name: Deploy Next.js to Azure

on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      # Instala TODO (incluye next)
      - name: Install dependencies
        run: npm install

      # Build de Next.js
      - name: Build
        run: npm run build

      - name: Login Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_094964F6745D423292A98D504295445A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EF33E86EEBE146B6AEB2C6743BC003E8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B234F667460246AFB0246A8FB28BF4D8 }}

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: "sorter-backoffice2-dev"
          package: .
